topic_best_5_women = {
    "-1_the_you_she_to": "Women Archetypes",
    "0_she_her_and_you": "Women Archetypes",
    "1_mother_mom_your mother_your": "Family roles",
    "2_wife_my wife_my_your wife": "Mariage",
    "3_karen_you_to_susan": "Women names",
    "4_queen_the queen_the_princess": "Royalty",
    "5_women_woman_the_you": "Women Archetypes",
    "6_divorce_papers_she_the": "Mariage",
    "7_summer_the summer_the_we": "Nature",
    "8_trophy_trophy wife_wife_your trophy": "Mariage",
    "9_wearing_wear_her_mother": "Fashion & appearance",
    "10_stone_the stone_age_sword": "History",
    "11_daughter_my daughter_to me_my": "Family roles",
    "12_she_dog_up after_how": "Animals"
}

topic_worst_5_women = {
    "-1_she_the_to_you": "Women Archetypes",
    "0_mom_mother_your_your mother": "Family roles",
    "1_lady_hey_hey lady_cake": "Women Archetypes",
    "2_wife_my wife_my_your wife": "Mariage",
    "3_neck_she_her_her neck": "Fashion & appearance",
    "4_ruff_she_the_her": "Women Archetypes",
    "5_hillary_clinton_the_president": "Politics",
    "6_women_women women_you_girls": "Women Archetypes",
    "7_queen_princess_the_the queen": "Royalty",
    "8_her name_name_her_is": "Women Archetypes",
    "9_she_me_her_told": "Women Archetypes",
    "10_fashion_her_dress_she": "Fashion & appearance",
    "11_stone_stepping stone_stepping_your stepping": "Miscellaneous",
    "12_recipe_mother_your_apple": "Food",
    "13_summer_the_autumn_nor": "Nature",
    "14_cat_she_mouse_the": "Animals",
    "15_she_her_to_stop": "Women Archetypes",
    "16_eat_she_in_to eat": "Food",
    "17_band_marching_she_drummer": "Arts & Music",
    "18_collar_she_her_the": "Fashion & appearance"
}

topic_best_5_men = {
    "-1_he_don_the_you": "Men Archetypes",
    "0_trump_president_donald_the trump": "Politics",
    "1_sir_menu_reservation_the menu": "Food",
    "2_feel_feel seen_don feel_don": "Social",
    "3_don worry_worry_fast_don": "Miscellaneous",
    "4_shoes_pants_wearing_wear": "Fashion & appearance",
    "5_dad_father_your father_your dad": "Family roles",
    "6_dog_the dog_dogs_park": "Animals",
    "7_rock_rock faster_rock and_faster": "Sport",
    "8_hands_size_feet_six feet": "Fashion & appearance",
    "9_king_the king_prince_live the": "Royalty",
    "10_water_pool_michael_swim": "Sport",
    "11_waiter_chef_soup_the chef": "Food",
    "12_patient_doc_doctor_appointment": "Health",
    "13_brother_your brother_your_my brother": "Family roles",
    "14_eat_feed_dinner_food": "Food",
    "15_died_he died_death_loved": "Death",
    "16_mouse_rat_mice_lab": "Animals",
    "17_houses_house_flipping_flip": "House",
    "18_bird_chicken_pigeon_cuckoo": "Animals",
    "19_piano_music_keith richards_keith": "Arts & Music",
    "20_cave_man cave_man_your man": "Men Archetypes",
    "21_tweet_tweets_tweeting_twitter": "Social",
    "22_last man_on earth_man on_earth": "Men Archetypes",
    "23_gravity_gravity of_the gravity_situation": "Miscellaneous",
    "24_insurance_life insurance_cover_health": "Money",
    "25_dark side_dark_friendly_side": "Pop Culture",
    "26_god_of god_acts of_acts": "Religion",
    "27_fish_whale_sharks_dolphins": "Animals",
    "28_climate_climate change_global warming_warming": "Climate",
    "29_jury_judge_the judge_the jury": "Work",
    "30_jack_know jack_bean_cloud": "Fantasy & mythology",
    "31_frank_be frank_frank with_frank you": "Men names",
    "32_plant_careful_he plant_be plant": "Nature",
    "33_glasses_hair_bald_my hair": "Fashion & appearance",
    "34_coming_coming he_it coming_himself": "Miscellaneous",
    "35_honor_witness_your honor_the witness": "Work",
    "36_middle_aged_middle aged_men": "Men Archetypes",
    "37_good boy_boy_good_who good": "Men Archetypes",
    "38_book_them_book club_club": "Arts & Music",
    "39_cat_cats_the cat_litter": "Animals",
    "40_vaccine_covid_the vaccine_vaccinated": "COVID & pandemic",
    "41_yard_leaves_neighbor_his leaves": "House",
    "42_son_best friend_friend_best": "Family roles",
    "43_toast_sorry sir_bread_sorry": "Food",
    "44_wall_the wall_for it_walls": "Politics",
    "45_horse_horses_the king_king horses": "Animals",
    "46_toilet_the toilet_bathroom_toilet paper": "House",
    "47_diversity_white_male_white male": "Men Archetypes",
    "48_moon_the moon_biden_man in": "Politics",
    "49_plane_road_far_flight": "Transport",
    "50_shotgun_riding shotgun_gun_riding": "Transport",
    "51_sales_salesman_on commission_bs": "Work",
    "52_yorker_new yorker_new_cartoon": "Pop Culture",
    "53_cloud_the cloud_clouds_know clouds": "Nature",
    "54_billy_billy the_the kid_kid": "Pop Culture",
    "55_the death_penalty_death penalty_death": "Death",
    "56_rabbit_rabbit out_hat_of hat": "Fantasy & mythology",
    "57_like your_don look_profile_look": "Social",
    "58_extinct_he extinct_be worth_worth": "Miscellaneous",
    "59_diet_paleo_paleo diet_milk": "Health",
    "60_carl_metaphor_sagan_carl sagan": "Public Figures",
    "61_mask_wearing mask_wear_wearing": "COVID & pandemic",
    "62_harold_harold this_golf course_golf": "Sport",
    "63_heart_tell him_the heart_heart to": "Health",
    "64_fire_discovered fire_fireman_burning man": "Miscellaneous",
    "65_he ll_ll be_be here_week": "Men Archetypes",
    "66_opponent_my opponent_spin_my": "Politics",
    "67_husband_ex_divorce_your ex": "Mariage",
    "68_sheep_wool_the sheep_clothing": "Animals",
    "69_from home_home_working from_work from": "Work",
    "70_john_you on_turn you_john you": "Men names",
    "71_gravity_the gravity_gravity of_situation": "Miscellaneous",
    "72_his work_work_his_work is": "Work",
    "73_stand up_stand_crawling_up": "Sport",
    "74_350_degrees_temperature_350 degrees": "Nature",
    "75_asleep_wake_sleep_bedtime": "Miscellaneous",
    "76_bush_the bush_two in_two": "Nature",
    "77_knight_tip_one knight_knight stands": "Fantasy & mythology",
    "78_lemons_lemonade_you lemons_when death": "Death",
    "79_drop_drop in_to drop_drops in": "Miscellaneous",
    "80_believe_exist_either he_believe him": "Religion",
    "81_side effects_effects_side_prescription": "Health",
    "82_ignore him_ignore_just ignore_him he": "Social",
    "83_square_pole_the square_peg": "Work",
    "84_clown_cop_clowns_good cop": "Pop Culture",
    "85_mortgage_reverse_reverse mortgage_upside down": "Money",
    "86_upside_upside down_down_his world": "Miscellaneous",
    "87_larry_it larry_larry got_to larry": "Men names",
    "88_george_george is_curious_beforeman grill": "Men names",
    "89_stocks_stock_bonds_in stocks": "Money",
    "90_yoga_rug_mat_carpet": "Sport",
    "91_arthur_merlin_arthur so_miller": "Fantasy & mythology",
    "92_hat_his hat_the hat_that hat": "Fashion & appearance",
    "93_hired him_hire_hired_resume": "Work",
    "94_tax_taxes_tax returns_returns": "Money",
    "95_australia_from australia_here from_moved here": "Miscellaneous",
    "96_count_count them_asleep_how many": "Miscellaneous",
    "97_period_jurassic_his jurassic_jurassic period": "History",
    "98_box_the box_outside the_outside": "Miscellaneous",
    "99_lawyer_attorney_courtesy_professional courtesy": "Work",
    "100_sniff_butt_smell_sniffing": "Animals",
    "101_cheese_the cheese_your cheese_cheese he": "Food",
    "102_bob_fred_bob we_bob finally": "Men names",
    "103_fit in_fit_don fit_to fit": "Miscellaneous",
    "104_mars_jupiter_pluto_venus": "Miscellaneous",
    "105_directions_for directions_ask_ask for": "Transport",
    "106_his past_past_caught up_caught": "Miscellaneous",
    "107_egg_nest_nest egg_the nest": "Miscellaneous",
    "108_wheel_the wheel_patent_invented": "History",
    "109_fox_fox news_news_hannity": "Miscellaneous",
    "110_coffee_mr coffee_coffee he_the coffee": "Food",
    "111_list_bucket_his bucket_bucket list": "Miscellaneous",
    "112_base_third base_to third_third": "Sport",
    "113_ted_ted he_ted to_ted talks": "Social",
    "114_drink_for drink_drink he_him over": "Food",
    "115_him up_bag_pick him_pick": "Miscellaneous",
    "116_chair_sofa_sit_to sit": "House",
    "117_french_the french_french restaurants_restaurants": "Food",
    "118_lance_lance lot_lot_me lance": "Men names",
    "119_jerry_ben_ben and_and jerry": "Pop Culture",
    "120_zoom_zoom background_background_don worry": "Miscellaneous",
    "121_rent_it rent_rent controlled_controlled": "House",
    "122_lawn_his lawn_the lawn_grass": "House",
    "123_change_to change_change don_like change": "Miscellaneous",
    "124_darwin_theory_evolved_selection": "History"
}

topic_worst_5_men = {
    "-1_he_you_the_to": "Men Archetypes",
    "0_don_look_you_you don": "Miscellaneous",
    "1_king_the king_horses_all the": "Royalty",
    "2_rock_rock and_climbing_the rock": "Sport",
    "3_serve_don serve_clown_we don": "Work",
    "4_invention_reinventing_inventor_he": "History",
    "5_pie_apple_adam_eve": "Religion",
    "6_cave_the cave_trained_arrest": "Miscellaneous",
    "7_piano_music_song_boxing": "Arts & Music",
    "8_peter_movie_book_bird": "Pop Culture",
    "9_duck_row_ducks_quack": "Animals",
    "10_license_sir_mph_speed": "Transport",
    "11_dad_father_your father_your": "Family roles",
    "12_dress_suit_fashion_sir": "Fashion & appearance",
    "13_wall_trump_the wall_tower": "Politics",
    "14_wave_trump_trump wave_waves": "Politics",
    "15_the wheel_wheel_wheel he_reinvent the": "History",
    "16_eat_him_feed_feed him": "Food",
    "17_attached_attached to_to me_very attached": "Social",
    "18_donut_doughnut_bagel_donuts": "Food",
    "19_separation_anxiety_separation anxiety_attachment": "Health",
    "20_hair_my hair_your hair_wash that": "Fashion & appearance",
    "21_leaves_rake_leaf_raking": "Nature",
    "22_soup_waiter_tornado_my soup": "Food",
    "23_shoes_boots_foot_those": "Fashion & appearance",
    "24_leash_park_dog_sir": "Animals",
    "25_leg_arm_and leg_arm and": "Miscellaneous",
    "26_extinct_be extinct_evolve_extinct he": "Miscellaneous",
    "27_climate_warming_global_global warming": "Climate",
    "28_dog_pet_dog he_dog star": "Animals",
    "29_god_their god_their_dyslexia": "Religion",
    "30_mars_rover_to mars_mars rover": "Miscellaneous",
    "31_walk_for walk_take him_him for": "Animals",
    "32_good boy_boy_good_who good": "Miscellaneous",
    "33_vegan_vegetarian_eat_vegan don": "Food",
    "34_wheel_invented_the wheel_invented the": "History",
    "35_whale_whale of_whales_of time": "Animals",
    "36_planet_legged_earthling_two legged": "Nature",
    "37_kite_park_kites_kite park": "Sport",
    "38_best friend_friend_best_man best": "Miscellaneous",
    "39_arthur_king arthur_merlin_it out": "Fantasy & mythology",
    "40_smell_sniff_to sniff_smells": "Animals",
    "41_honey_bear_honey bear_pooh": "Pop Culture",
    "42_cat_the cat_cats_blind": "Animals",
    "43_sheep_the sheep_wolf_peep": "Animals",
    "44_dinosaur_ankylosaurus_an ankylosaurus_part": "History",
    "45_voted_voted for_vote_vote for": "Politics",
    "46_mountain_the mountain_summit_he said": "Nature",
    "47_gluten_gluten free_free_it gluten": "Food",
    "48_followed_me home_followed me_he followed": "Social",
    "49_cloud_angry_weather_the weather": "Nature",
    "50_john_johnny_johnny is_marsha": "Men names",
    "51_george_rabbit_george is_george the": "Pop Culture",
    "52_paleo_diet_paleo diet_the paleo": "Health",
    "53_manager_don hire_diversity_hire": "Work",
    "54_donald_the donald_donald donald_is donald": "Politics",
    "55_sharks_shark_water_on water": "Animals",
    "56_fish_seafood_the fish_eel": "Animals",
    "57_man_size_men_all men": "Men Archetypes",
    "58_mouse_mice_blind_blind mice": "Animals",
    "59_to go_go out_go_out": "Social",
    "60_tweet_twitter_tweets_trump": "Politics",
    "61_island_an island_no man_man is": "Miscellaneous",
    "62_teething_just teething_teething he_teeth": "Miscellaneous",
    "63_brother_big brother_your brother_uncle": "Family roles",
    "64_leader_their leader_their_leader he": "Politics",
    "65_bark_his bark_his bite_worse": "Animals",
    "66_dinner_chef_cook_served sir": "Food",
    "67_keep him_keep_can we_we keep": "Miscellaneous",
    "68_train_the train_tracks_trains": "Transport",
    "69_weight_shoulders_the weight_feel": "Health",
    "70_boat_the boat_cruise_rock the": "Transport",
    "71_insurance_health_health care_have insurance": "Health",
    "72_up his_poop_leader_his poop": "Politics",
    "73_elephant_elephant in_the elephant_the room": "Social",
    "74_gravity_of gravity_gravity he_gravity of": "Miscellaneous",
    "75_blind_blinders_blinders on_eye": "Miscellaneous",
    "76_bite_don bite_chew_doesn bite": "Miscellaneous",
    "77_him_attention_ignore_ignore him": "Miscellaneous",
    "78_rescue_he rescue_rescue he_rescued": "Miscellaneous",
    "79_monkeys_shakespeare_the monkeys_shakespeare but": "Arts & Music",
    "80_halloween_costume_for halloween_halloween costume": "Miscellaneous",
    "81_chairman_the chairman_board_chairman of": "Work",
    "82_prince_prince charming_charming_the prince": "Royalty",
    "83_room_men room_the men_the room": "Men Archetypes",
    "84_frank_frank is_raking_frank with": "Men names",
    "85_pizza_the pizza_pepperoni_plane": "Food",
    "86_patients_therapist_mr_my patients": "Health",
    "87_tail_his tail_his_tail is": "Animals",
    "88_burger_burger king_burgers_king": "Food",
    "89_snow_frosty_snowman_frosty he": "Nature",
    "90_ball_no batter_batter_balls": "Sport",
    "91_sword_the sword_desk_pull": "Fantasy & mythology",
    "92_business_scheme_pyramid scheme_business is": "Money",
    "93_jerry_tom_and jerry_ho": "Pop Culture",
    "94_new yorker_yorker_new_new york": "Pop Culture",
    "95_harold_harold it_salesman_me harold": "Men names",
    "96_heel_to heel_heel he_him to": "Miscellaneous",
    "97_dub_tub_bath_rub dub": "House",
    "98_yeti_yeti he_yeti yeti_is yeti": "Fantasy & mythology",
    "99_egg_eggs_yolk_omelet": "Food",
    "100_joe_beat down_pitts_pitts washington": "Miscellaneous",
    "101_told him_the wheel_wheel_reinvent": "History",
    "102_phone_call_iphone_cell": "Miscellaneous",
    "103_jack_jump_something_ripper": "Pop Culture",
    "104_henry_mancini_boom_henry henry": "Arts & Music",
    "105_trump_anti_anti trump_gays": "Politics",
    "106_beam_scotty_scottie_beam me": "Pop Culture",
    "107_sweet_look sweet_he looks_look": "Fashion & appearance",
    "108_lion_the lion_den_lion to": "Animals",
    "109_the fastest_fastest_down_up he": "Miscellaneous",
    "110_buns_anaconda_bun_hun": "Animals",
    "111_snake_snake oil_oil_was snake": "Animals",
    "112_boys_shop boys_pet shop_beach boys": "Miscellaneous"
}
